spring.application.name=homework

spring.datasource.url=jdbc:postgresql://localhost:5432/Diploma-Thesis-ADS
spring.datasource.username=postgres
spring.datasource.password=Jnlfktrf@1974
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

logging.level.ru.skypro.homework=DEBUG